### ISSUE TITLE
Frontend: Admin Sign Up Page

### ISSUE THREAD

**Issue by TonyPhan0505** [TonyPhan0505/Oceanward-Web-App#57]
The frontend url for the admin sign up page should be "/admin/dang_ky". Look at the file App.js in the frontend directory and look up react router dom package to know how to set a frontend route to the page.

Create a new branch for your issue and clone it. Open the project and look through the current design to get a feel of how your design should be. However, also feel free to suggest any changes to the current design.

ALL TEXT ON THIS PAGE SHOULD BE DISPLAYED IN VIETNAMESE.

DON'T WORRY ABOUT CONNECTING THE FRONTEND AND THE BACKEND NOW. THAT MEANS DON'T WORRY ABOUT ANY DATABASE STUFF.

The admin sign up page should include the following input fields:

- Username
- Password
- Admin Key (will be used to authenticate the admin later when the admin logs in)

**Comment by umesh-9** [comment]
#57 admin sign up page created  once check it
